### PR TITLE
Update Command JSON encoding so that it works for generic commands.

### PR DESCRIPTION
**Pull request by gonzojive**

### CODE REVIEW

**Comment by zopieux** [comment]
Wow, what were the odds – the sheer coincidence of this timing, almost 2 years after this repository was shown any love. I fixed this exact bug on my fork a few days ago and meant to send a PR this weekend. Didn't check for existing PRs, so here we are, I opened #8 which basically does the same thing.

**Comment by gonzojive** [comment]
Cool. The biggest difference is in the testing style, I think. I have grown used to table-driven test in Go and using cmp.Diff. I'm not familiar with assert.

**Comment by zopieux** [comment]
Yeah I don't know, I just got inspired by the other tests in the file. Your round-trip thingy seems nice. Can you make sure to also test for omitted params like I do? I know from experiencing it that Google sends such payloads. Then your PR could obsolete mine. :smiley:

**Comment by rmrobinson** [comment]
@gonzojive I appreciate the PR! I agree that table-driven tests are much nicer, thank you for introducing them here.

@zopieux thanks for sharing the insight that Google can send payloads lacking params - I haven't personally experienced that yet so it's good to know. If we can add a test to ensure proper handling of them here @gonzojive I would be more than happy to merge this PR.

Thank you both for your contributions back to this library.

**Comment by gonzojive** [comment]
Should be ready for review now. I pulled in changes from #8.

I recommend using a squash commit to merge these changes and preserving the tag that attributes changes to @zopieux.

**Review by rmrobinson — APPROVED** [review]

**Comment by rmrobinson** [comment]
Thanks both - squash merged as suggested.

**Pull request merged**
